import { boolean, integer, jsonb, pgTable, text, timestamp, uuid, bigint } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('emailVerified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
  role: text('role').notNull().default('USER'),
  username: text('username'),
  inviteCode: text('invite_code'),
  referredByCode: text('referred_by_code'),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(), expiresAt: timestamp('expiresAt', { withTimezone: true }).notNull(), token: text('token').notNull().unique(),
  createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull(),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt', { withTimezone: true }), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt', { withTimezone: true }), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt', { withTimezone: true }).notNull(), createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
})

export const wallets = pgTable('quantix_wallets', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull().unique(), availableMinor: bigint('available_minor', { mode: 'number' }).notNull().default(0), investedMinor: bigint('invested_minor', { mode: 'number' }).notNull().default(0), profitMinor: bigint('profit_minor', { mode: 'number' }).notNull().default(0), currency: text('currency').notNull().default('NGN'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const plans = pgTable('quantix_plans', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), description: text('description').notNull(), minimumMinor: bigint('minimum_minor', { mode: 'number' }).notNull(), maximumMinor: bigint('maximum_minor', { mode: 'number' }).notNull(), returnBps: integer('return_bps').notNull(), durationDays: integer('duration_days').notNull(), terms: text('terms').notNull(), category: text('category').notNull().default('MONTHLY'), active: boolean('active').notNull().default(false), displayOrder: integer('display_order').notNull().default(0), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const paymentAccounts = pgTable('quantix_payment_accounts', { id: uuid('id').defaultRandom().primaryKey(), label: text('label').notNull(), bankName: text('bank_name').notNull(), accountName: text('account_name').notNull(), accountNumber: text('account_number').notNull(), active: boolean('active').notNull().default(true), displayOrder: integer('display_order').notNull().default(0), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const investments = pgTable('quantix_investments', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), depositId: uuid('deposit_id'), planId: uuid('plan_id').notNull(), planNameSnapshot: text('plan_name_snapshot').notNull(), principalMinor: bigint('principal_minor', { mode: 'number' }).notNull(), returnBpsSnapshot: integer('return_bps_snapshot').notNull(), profitMinor: bigint('profit_minor', { mode: 'number' }).notNull(), maturityMinor: bigint('maturity_minor', { mode: 'number' }).notNull(), durationDaysSnapshot: integer('duration_days_snapshot').notNull(), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), maturesAt: timestamp('matures_at', { withTimezone: true }).notNull(), status: text('status').notNull().default('ACTIVE'), maturedAt: timestamp('matured_at', { withTimezone: true }) })
export const ledgerEntries = pgTable('quantix_ledger_entries', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), reference: text('reference').notNull().unique(), type: text('type').notNull(), amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(), direction: text('direction').notNull(), status: text('status').notNull().default('POSTED'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const payoutAccounts = pgTable('quantix_payout_accounts', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), bankName: text('bank_name').notNull(), accountName: text('account_name').notNull(), accountNumber: text('account_number').notNull(), verifiedStatus: text('verified_status').notNull().default('UNAVAILABLE'), isDefault: boolean('is_default').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const deposits = pgTable('quantix_deposits', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(), planId: uuid('plan_id'), paymentAccountId: uuid('payment_account_id'), senderName: text('sender_name'), transferReference: text('transfer_reference').notNull(), proofUrl: text('proof_url'), paymentProofName: text('payment_proof_name'), status: text('status').notNull().default('PENDING'), adminNote: text('admin_note'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), reviewedAt: timestamp('reviewed_at', { withTimezone: true }) })
export const withdrawals = pgTable('quantix_withdrawals', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(), feeMinor: bigint('fee_minor', { mode: 'number' }).notNull().default(0), netMinor: bigint('net_minor', { mode: 'number' }).notNull(), payoutAccountSnapshot: jsonb('payout_account_snapshot').notNull(), status: text('status').notNull().default('PENDING'), adminNote: text('admin_note'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), processedAt: timestamp('processed_at', { withTimezone: true }) })
export const notifications = pgTable('quantix_notifications', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), type: text('type').notNull(), title: text('title').notNull(), body: text('body').notNull(), deliveryStatus: text('delivery_status').notNull().default('IN_APP'), readAt: timestamp('read_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const auditLogs = pgTable('quantix_audit_logs', { id: uuid('id').defaultRandom().primaryKey(), actorId: text('actor_id'), actorRole: text('actor_role'), action: text('action').notNull(), targetType: text('target_type').notNull(), targetId: text('target_id'), reason: text('reason'), beforeState: jsonb('before_state'), afterState: jsonb('after_state'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const referrals = pgTable('quantix_referrals', { id: uuid('id').defaultRandom().primaryKey(), referrerUserId: text('referrer_user_id').notNull(), referredUserId: text('referred_user_id').notNull(), inviteCode: text('invite_code').notNull(), status: text('status').notNull().default('PENDING'), rewardMinor: bigint('reward_minor', { mode: 'number' }).notNull().default(0), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), qualifiedAt: timestamp('qualified_at', { withTimezone: true }) })
export const supportThreads = pgTable('quantix_support_threads', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), subject: text('subject').notNull(), status: text('status').notNull().default('OPEN'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const supportMessages = pgTable('quantix_support_messages', { id: uuid('id').defaultRandom().primaryKey(), threadId: uuid('thread_id').notNull(), userId: text('user_id').notNull(), body: text('body').notNull(), senderType: text('sender_type').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const luckyDraws = pgTable('quantix_lucky_draws', { id: uuid('id').defaultRandom().primaryKey(), title: text('title').notNull(), description: text('description').notNull(), rewardType: text('reward_type').notNull(), rewardMinor: bigint('reward_minor', { mode: 'number' }), alternateReward: text('alternate_reward'), entryCostMinor: bigint('entry_cost_minor', { mode: 'number' }).notNull().default(0), opensAt: timestamp('opens_at', { withTimezone: true }).notNull().defaultNow(), closesAt: timestamp('closes_at', { withTimezone: true }).notNull(), status: text('status').notNull().default('OPEN'), winnerUserId: text('winner_user_id'), winnerEntryId: uuid('winner_entry_id'), claimedAt: timestamp('claimed_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const luckyEntries = pgTable('quantix_lucky_entries', { id: uuid('id').defaultRandom().primaryKey(), drawId: uuid('draw_id').notNull(), userId: text('user_id').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const walletLedger = pgTable('quantix_wallet_ledger', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), reference: text('reference').notNull().unique(), type: text('type').notNull(), amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(), status: text('status').notNull().default('POSTED'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const supportSettings = pgTable('quantix_support_settings', { id: uuid('id').defaultRandom().primaryKey(), email: text('email').notNull(), whatsapp: text('whatsapp'), hours: text('hours').notNull().default('Mon-Fri, 9am-5pm'), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const withdrawalSettings = pgTable('quantix_withdrawal_settings', { id: uuid('id').defaultRandom().primaryKey(), timezone: text('timezone').notNull().default('Africa/Lagos'), enabledDays: text('enabled_days').array().notNull().default(['MON','TUE','WED','THU','FRI']), startTime: text('start_time').notNull().default('09:00'), endTime: text('end_time').notNull().default('17:00'), minimumMinor: bigint('minimum_minor', { mode: 'number' }).notNull().default(100000), maximumMinor: bigint('maximum_minor', { mode: 'number' }), enabled: boolean('enabled').notNull().default(true), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const userPayoutAccounts = pgTable('quantix_payout_accounts', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), bankName: text('bank_name').notNull(), accountName: text('account_name').notNull(), accountNumber: text('account_number').notNull(), isDefault: boolean('is_default').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const withdrawalRequests = pgTable('quantix_withdrawals', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), payoutAccountId: uuid('payout_account_id').notNull(), amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(), feeMinor: bigint('fee_minor', { mode: 'number' }).notNull().default(0), netMinor: bigint('net_minor', { mode: 'number' }).notNull(), status: text('status').notNull().default('PENDING'), adminNote: text('admin_note'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), processedAt: timestamp('processed_at', { withTimezone: true }) })

