'use server'
import { and, asc, desc, eq } from 'drizzle-orm'
import { headers } from 'next/headers'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { auditLogs, plans, paymentAccounts, withdrawalRequests, withdrawalSettings, user } from '@/lib/db/schema'
async function requireAdmin() { const session = await auth.getSession(); if (!session?.user) throw new Error('Unauthorized'); const [record] = await db.select({ role: user.role }).from(user).where(eq(user.id, session.user.id)).limit(1); if (record?.role !== 'ADMIN') throw new Error('Forbidden'); return session.user.id }
export async function getAdminControlData() { await requireAdmin(); const [planRows, accountRows, withdrawals, settings] = await Promise.all([db.select().from(plans).orderBy(asc(plans.category), asc(plans.displayOrder)), db.select().from(paymentAccounts).orderBy(asc(paymentAccounts.displayOrder)), db.select().from(withdrawalRequests).orderBy(desc(withdrawalRequests.createdAt)).limit(50), db.select().from(withdrawalSettings).limit(1)]); return { plans: planRows, accounts: accountRows, withdrawals, settings: settings[0] || null } }
const planSchema = z.object({ name: z.string().min(2), description: z.string().min(2), category: z.enum(['DAILY','WEEKLY','MONTHLY']), minimumMinor: z.number().int().positive(), maximumMinor: z.number().int().positive(), returnBps: z.number().int().positive(), durationDays: z.number().int().positive(), terms: z.string().min(2) })
export async function createPlan(input: z.input<typeof planSchema>) { const actorId = await requireAdmin(); const data = planSchema.parse(input); const [plan] = await db.insert(plans).values(data).returning(); await db.insert(auditLogs).values({ actorId, actorRole: 'ADMIN', action: 'CREATE_PLAN', targetType: 'PLAN', targetId: plan.id }); revalidatePath('/admin'); return plan }
export async function updateWithdrawalSettings(input: { timezone: string; enabledDays: string[]; startTime: string; endTime: string; minimumMinor: number; maximumMinor?: number | null; enabled: boolean }) { const actorId = await requireAdmin(); const data = input; const [existing] = await db.select().from(withdrawalSettings).limit(1); const result = existing ? await db.update(withdrawalSettings).set({ ...data, updatedAt: new Date() }).where(eq(withdrawalSettings.id, existing.id)).returning() : await db.insert(withdrawalSettings).values(data).returning(); await db.insert(auditLogs).values({ actorId, actorRole: 'ADMIN', action: 'UPDATE_WITHDRAWAL_WINDOW', targetType: 'WITHDRAWAL_SETTINGS' }); revalidatePath('/admin'); return result[0] }
export async function reviewWithdrawal(id: string, status: 'APPROVED' | 'REJECTED', adminNote?: string) { const actorId = await requireAdmin(); const [item] = await db.update(withdrawalRequests).set({ status, adminNote, processedAt: new Date() }).where(and(eq(withdrawalRequests.id, id), eq(withdrawalRequests.status, 'PENDING'))).returning(); if (!item) throw new Error('Withdrawal already processed'); await db.insert(auditLogs).values({ actorId, actorRole: 'ADMIN', action: `WITHDRAWAL_${status}`, targetType: 'WITHDRAWAL', targetId: id, reason: adminNote }); revalidatePath('/admin'); return item }
