'use server'

import { and, desc, eq, gte, lte, sql } from 'drizzle-orm'
import { headers } from 'next/headers'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { luckyDraws, luckyEntries, notifications, walletLedger } from '@/lib/db/schema'

async function sessionUser() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error('Unauthorized'); return session.user.id }
export async function getOpenDraws() { const userId = await sessionUser(); return db.select({ draw: luckyDraws, entryId: luckyEntries.id }).from(luckyDraws).leftJoin(luckyEntries, and(eq(luckyEntries.drawId, luckyDraws.id), eq(luckyEntries.userId, userId))).where(and(eq(luckyDraws.status, 'OPEN'), lte(luckyDraws.opensAt, new Date()), gte(luckyDraws.closesAt, new Date()))).orderBy(desc(luckyDraws.closesAt)) }
export async function joinDraw(drawId: string) { const userId = await sessionUser(); const id = z.string().uuid().parse(drawId); const [draw] = await db.select().from(luckyDraws).where(and(eq(luckyDraws.id, id), eq(luckyDraws.status, 'OPEN'))).limit(1); if (!draw || draw.closesAt < new Date()) throw new Error('This draw is closed'); const existing = await db.select({ id: luckyEntries.id }).from(luckyEntries).where(and(eq(luckyEntries.drawId, id), eq(luckyEntries.userId, userId))).limit(1); if (existing.length) throw new Error('You have already joined this draw'); const [entry] = await db.insert(luckyEntries).values({ drawId: id, userId }).returning(); revalidatePath('/'); return entry }
export async function claimReward(drawId: string) { const userId = await sessionUser(); const id = z.string().uuid().parse(drawId); const [draw] = await db.select().from(luckyDraws).where(and(eq(luckyDraws.id, id), eq(luckyDraws.winnerUserId, userId))).limit(1); if (!draw || draw.claimedAt) throw new Error('Reward is unavailable'); if (draw.rewardType === 'CASH' && draw.rewardMinor) { await db.insert(walletLedger).values({ userId, reference: `LUCKY-${draw.id}`, type: 'LUCKY_WIN', amountMinor: draw.rewardMinor, metadata: { drawId: draw.id } }).onConflictDoNothing(); } await db.update(luckyDraws).set({ claimedAt: new Date(), status: 'CLAIMED', updatedAt: new Date() }).where(eq(luckyDraws.id, id)); await db.insert(notifications).values({ userId, type: 'LUCKY_CLAIMED', title: 'Reward claimed', body: draw.rewardType === 'CASH' ? 'Your cash reward was added to your wallet.' : 'Your reward is now with the operations team.' }); revalidatePath('/'); return true }
export async function closeDueDraws() { const due = await db.select().from(luckyDraws).where(and(eq(luckyDraws.status, 'OPEN'), lte(luckyDraws.closesAt, new Date()))); for (const draw of due) { const entries = await db.select().from(luckyEntries).where(eq(luckyEntries.drawId, draw.id)); if (!entries.length) { await db.update(luckyDraws).set({ status: 'CLOSED', updatedAt: new Date() }).where(eq(luckyDraws.id, draw.id)); continue } const winner = entries[Math.floor(Math.random() * entries.length)]; await db.update(luckyDraws).set({ status: 'WON', winnerUserId: winner.userId, winnerEntryId: winner.id, updatedAt: new Date() }).where(and(eq(luckyDraws.id, draw.id), eq(luckyDraws.status, 'OPEN'))); await db.insert(notifications).values({ userId: winner.userId, type: 'LUCKY_WIN', title: 'You won Lucky Wish', body: draw.rewardType === 'CASH' ? 'Your cash reward is ready to claim.' : `Your ${draw.alternateReward || 'reward'} is ready to claim.` }); } return due.length }
