'use server'

import { and, desc, eq, sql } from 'drizzle-orm'
import { headers } from 'next/headers'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { investments, ledgerEntries, notifications, referrals, user, userPayoutAccounts, wallets, withdrawalRequests, withdrawalSettings } from '@/lib/db/schema'

async function getSession() { const session = await auth.getSession(); if (!session?.user) throw new Error('Unauthorized'); return session }
async function getUserId() { return (await getSession()).user.id }

export async function getWalletSnapshot() {
  const userId = await getUserId()
  const [wallet] = await db.select().from(wallets).where(eq(wallets.userId, userId)).limit(1)
  const ledger = await db.select().from(ledgerEntries).where(eq(ledgerEntries.userId, userId)).orderBy(desc(ledgerEntries.createdAt)).limit(12)
  const active = await db.select().from(investments).where(and(eq(investments.userId, userId), eq(investments.status, 'ACTIVE')))
  const credits = ledger.filter((entry) => entry.direction === 'CREDIT').reduce((sum, entry) => sum + entry.amountMinor, 0)
  const debits = ledger.filter((entry) => entry.direction === 'DEBIT').reduce((sum, entry) => sum + entry.amountMinor, 0)
  return { wallet, ledger, active, trendPercent: credits ? Math.round(((credits - debits) / credits) * 100) : 0 }
}
export async function getInvestedPlanIds() { const userId = await getUserId(); const rows = await db.select({ planId: investments.planId }).from(investments).where(eq(investments.userId, userId)); return rows.map((row) => row.planId) }
export async function processMaturities() { const now = new Date(); const due = await db.select().from(investments).where(and(eq(investments.status, 'ACTIVE'), sql`${investments.maturesAt} <= ${now}`)); for (const investment of due) { const updated = await db.update(investments).set({ status: 'MATURED', maturedAt: now }).where(and(eq(investments.id, investment.id), eq(investments.status, 'ACTIVE'))).returning({ id: investments.id }); if (!updated.length) continue; await db.insert(ledgerEntries).values({ userId: investment.userId, reference: `maturity:${investment.id}`, type: 'MATURITY_PAYOUT', amountMinor: investment.maturityMinor, direction: 'CREDIT', metadata: { investmentId: investment.id } }).onConflictDoNothing(); await db.insert(wallets).values({ userId: investment.userId, availableMinor: investment.maturityMinor }).onConflictDoNothing(); await db.update(wallets).set({ availableMinor: sql`${wallets.availableMinor} + ${investment.maturityMinor}`, profitMinor: sql`${wallets.profitMinor} + ${investment.profitMinor}`, investedMinor: sql`${wallets.investedMinor} - ${investment.principalMinor}`, updatedAt: now }).where(eq(wallets.userId, investment.userId)); } revalidatePath('/'); return due.length }

export async function getReferralSnapshot() { const session = await getSession(); const [profile] = await db.select({ username: user.username, inviteCode: user.inviteCode }).from(user).where(eq(user.id, session.user.id)).limit(1); const rows = await db.select().from(referrals).where(eq(referrals.referrerUserId, session.user.id)).orderBy(desc(referrals.createdAt)); const earned = rows.filter((row) => row.status === 'QUALIFIED').reduce((sum, row) => sum + row.rewardMinor, 0); const pending = rows.filter((row) => row.status !== 'QUALIFIED').reduce((sum, row) => sum + row.rewardMinor, 0); return { profile, referrals: rows, earned, pending, link: profile?.inviteCode ? `${process.env.NEXT_PUBLIC_APP_URL || ''}/sign-up?ref=${profile.inviteCode}` : '' } }
export async function addPayoutAccount(input: z.input<typeof payoutSchema>) { const userId = await getUserId(); const data = payoutSchema.parse(input); const existing = await db.select({ id: userPayoutAccounts.id }).from(userPayoutAccounts).where(eq(userPayoutAccounts.userId, userId)); if (existing.length >= 2) throw new Error('You can save up to two payout accounts'); const [account] = await db.insert(userPayoutAccounts).values({ ...data, userId, isDefault: existing.length === 0 }).returning(); revalidatePath('/'); return account }
const payoutSchema = z.object({ bankName: z.string().trim().min(2).max(80), accountName: z.string().trim().min(2).max(120), accountNumber: z.string().regex(/^\d{10}$/) })
export async function getUserPayoutAccounts() { const userId = await getUserId(); return db.select().from(userPayoutAccounts).where(eq(userPayoutAccounts.userId, userId)).orderBy(desc(userPayoutAccounts.createdAt)) }
export async function requestWithdrawal(input: { payoutAccountId: string; amountMinor: number }) { const userId = await getUserId(); const data = z.object({ payoutAccountId: z.string().uuid(), amountMinor: z.number().int().positive() }).parse(input); const [settings] = await db.select().from(withdrawalSettings).limit(1); if (settings?.enabled) { const now = new Date(); const day = new Intl.DateTimeFormat('en-US', { weekday: 'short', timeZone: settings.timezone }).format(now).toUpperCase(); const time = new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: settings.timezone }).format(now); if (!settings.enabledDays.includes(day) || time < settings.startTime || time > settings.endTime) throw new Error(`Withdrawals are open ${settings.startTime}–${settings.endTime} (${settings.timezone})`); if (data.amountMinor < settings.minimumMinor || (settings.maximumMinor && data.amountMinor > settings.maximumMinor)) throw new Error('Amount is outside the configured withdrawal limits'); } const [wallet] = await db.select().from(wallets).where(eq(wallets.userId, userId)).limit(1); if (!wallet || wallet.availableMinor < data.amountMinor) throw new Error('Insufficient wallet balance'); const [account] = await db.select().from(userPayoutAccounts).where(and(eq(userPayoutAccounts.id, data.payoutAccountId), eq(userPayoutAccounts.userId, userId))).limit(1); if (!account) throw new Error('Payout account not found'); const [request] = await db.insert(withdrawalRequests).values({ userId, payoutAccountId: account.id, amountMinor: data.amountMinor, netMinor: data.amountMinor }).returning(); await db.update(wallets).set({ availableMinor: sql`${wallets.availableMinor} - ${data.amountMinor}` }).where(eq(wallets.userId, userId)); const [admin] = await db.select({ id: user.id }).from(user).where(eq(user.role, 'ADMIN')).limit(1); if (admin) await db.insert(notifications).values({ userId: admin.id, type: 'WITHDRAWAL_REQUEST', title: 'New withdrawal request', body: `A withdrawal of ₦${Math.round(data.amountMinor / 100).toLocaleString('en-NG')} requires review.`, deliveryStatus: 'IN_APP' }); revalidatePath('/'); return request }
