'use client'

import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft, RefreshCw, Shield, Users, Wallet, TrendingUp, Landmark, Gift, Bell, ScrollText, Settings, Archive, RotateCcw, Save, Send, Search } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { getAdminCenter,savePlan,archivePlan,setUserState,savePolicy,sendAdminNotification,createDraw,toggleDraw,updateReferral,archivePayout } from '@/app/actions/admin-center'
import { adjustUserBalance,reviewDeposit } from '@/app/actions/admin'
import { reviewWithdrawal } from '@/app/actions/control'
import { setPaymentAccountActive } from '@/app/actions/payment-accounts'

const naira=(m:number)=>'₦'+(Number(m)/100).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})
const date=(v:any)=>v?new Date(v).toLocaleString('en-NG'):'—'

export default function AdminPage(){
 const router=useRouter();const [data,setData]=useState<any>(null);const [tab,setTab]=useState('overview');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [q,setQ]=useState('')
 const [amount,setAmount]=useState('');const [reason,setReason]=useState('');const [userId,setUserId]=useState('')
 const [plan,setPlan]=useState<any>({name:'',description:'',category:'MONTHLY',minimumMinor:1000000,maximumMinor:1000000,returnBps:500,durationDays:30,terms:'',purchaseBonusMinor:0,active:true,displayOrder:1})
 const [policy,setPolicy]=useState<any>({timezone:'Africa/Lagos',enabledDays:['MON','TUE','WED','THU','FRI'],startTime:'09:00',endTime:'17:00',minimumMinor:100000,maximumMinor:null,enabled:true})
 const [msg,setMsg]=useState<any>({userId:'',title:'',body:'',type:'SYSTEM'})
 const [draw,setDraw]=useState<any>({title:'',description:'',rewardType:'CASH',rewardMinor:0,alternateReward:'',entryCostMinor:0,opensAt:'',closesAt:''})
 const load=async()=>{try{setError('');const d=await getAdminCenter();setData(d);if(d.settings)setPolicy({timezone:d.settings.timezone,enabledDays:d.settings.enabled_days,startTime:d.settings.start_time,endTime:d.settings.end_time,minimumMinor:Number(d.settings.minimum_minor),maximumMinor:d.settings.maximum_minor==null?null:Number(d.settings.maximum_minor),enabled:d.settings.enabled})}catch(e){setError(e instanceof Error?e.message:'Unable to load control center')}}
 useEffect(()=>{void load()},[])
 const act=async(k:string,fn:()=>Promise<any>)=>{try{setBusy(k);setError('');await fn();await load()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}}
 const users=useMemo(()=>data?.profiles?.filter((u:any)=>(String(u.name)+' '+String(u.username)+' '+u.id).toLowerCase().includes(q.toLowerCase()))||[],[data,q])
 if(!data)return <main className="admin-shell"><div className="admin-frame"><div className="admin-loading">Loading full control center…</div></div></main>
 const tabs=[['overview','Overview',Shield],['users','Users',Users],['wallet','Wallet',Wallet],['deposits','Deposits',Landmark],['withdrawals','Withdrawals',Wallet],['plans','Plans',TrendingUp],['referrals','Referrals',Users],['lucky','Lucky Wish',Gift],['notifications','Notifications',Bell],['accounts','Bank Accounts',Landmark],['payouts','Payout Accounts',Landmark],['ledger','Ledger',ScrollText],['audit','Audit Logs',ScrollText],['settings','Settings',Settings]]
 return <main className="admin-shell"><div className="admin-frame max-w-7xl">
  <header className="sticky top-0 z-20 border-b border-white/10 bg-black/80 px-4 py-4 backdrop-blur-xl"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button className="icon-button" onClick={()=>router.back()}><ArrowLeft size={17}/></button><div className="brand-mark">Q</div><div><strong>quantix</strong><span className="block text-xs tracking-[.25em] opacity-60">PRIME CONTROL CENTER</span></div></div><button className="secondary-button" onClick={load}><RefreshCw size={16}/> Refresh</button></div><nav className="mt-4 flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,label,I]:any)=><button key={id} onClick={()=>setTab(id)} className={tab===id?'primary-button whitespace-nowrap':'secondary-button whitespace-nowrap'}><I size={15}/>{label}</button>)}</nav></header>
  {error&&<div className="admin-error m-4"><Shield size={17}/>{error}</div>}
  <section className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4">{[['Users',data.profiles.length],['Live plans',data.plans.filter((x:any)=>x.active&&!x.deleted_at).length],['Pending deposits',data.deposits.filter((x:any)=>x.status==='PENDING').length],['Pending withdrawals',data.withdrawals.filter((x:any)=>x.status==='PENDING').length]].map((x:any)=><div className="rounded-3xl border border-white/10 bg-white/5 p-5" key={x[0]}><div className="text-sm opacity-60">{x[0]}</div><div className="mt-2 text-3xl font-semibold">{x[1]}</div></div>)}</section>
  <div className="p-4">
   {tab==='overview'&&<div className="grid gap-4 lg:grid-cols-2"><Panel title="Pending deposits">{data.deposits.filter((x:any)=>x.status==='PENDING').map((x:any)=><Row key={x.id} title={naira(x.amount_minor)} meta={x.user_id+' · '+x.transfer_reference}><button className="primary-button" onClick={()=>act(x.id,()=>reviewDeposit({id:x.id,status:'APPROVED'}))}>Approve</button><button className="secondary-button" onClick={()=>act(x.id,()=>reviewDeposit({id:x.id,status:'REJECTED',reason}))}>Reject</button></Row>)}</Panel><Panel title="Recent audit activity">{data.audits.slice(0,20).map((x:any)=><Row key={x.id} title={x.action} meta={x.target_type+' · '+date(x.created_at)}/>)}</Panel></div>}
   {tab==='users'&&<Panel title="User accounts"><div className="mb-4 flex gap-2"><Search className="mt-3 opacity-50"/><input className="account-form flex-1" placeholder="Search name, username or UUID" value={q} onChange={e=>setQ(e.target.value)}/></div>{users.map((u:any)=><Row key={u.id} title={(u.name||'Unnamed')+' · '+(u.username||'No username')} meta={u.status+' · '+u.role+' · '+u.id}><button className="secondary-button" onClick={()=>{setUserId(u.id);setTab('wallet')}}>Wallet</button>{u.status==='ACTIVE'?<button className="secondary-button" onClick={()=>act(u.id,()=>setUserState(u.id,'SUSPENDED','Administrative suspension'))}>Suspend</button>:<button className="primary-button" onClick={()=>act(u.id,()=>setUserState(u.id,'ACTIVE','Administrative restoration'))}><RotateCcw size={15}/>Activate</button>}</Row>)}</Panel>}
   {tab==='wallet'&&<Panel title="Audited wallet control"><p className="admin-copy">Positive amount credits. Negative amount debits. The existing atomic financial function and audit log are used.</p><div className="grid gap-2 sm:grid-cols-3"><input className="account-form" placeholder="User UUID" value={userId} onChange={e=>setUserId(e.target.value)}/><input className="account-form" placeholder="Amount ₦" value={amount} onChange={e=>setAmount(e.target.value)}/><input className="account-form" placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/></div><button className="primary-button mt-3" onClick={()=>act('balance',()=>adjustUserBalance({userId,amountMinor:Math.round(Number(amount)*100),reason}))}><Save size={15}/>Apply adjustment</button></Panel>}
   {tab==='deposits'&&<Panel title="All deposits">{data.deposits.map((x:any)=><Row key={x.id} title={x.status+' · '+naira(x.amount_minor)} meta={x.user_id+' · '+date(x.created_at)}>{x.status==='PENDING'&&<><button className="primary-button" onClick={()=>act(x.id,()=>reviewDeposit({id:x.id,status:'APPROVED'}))}>Approve</button><button className="secondary-button" onClick={()=>act(x.id,()=>reviewDeposit({id:x.id,status:'REJECTED',reason}))}>Reject</button></>}</Row>)}</Panel>}
   {tab==='withdrawals'&&<Panel title="All withdrawals">{data.withdrawals.map((x:any)=><Row key={x.id} title={x.status+' · '+naira(x.amount_minor)} meta={x.user_id+' · net '+naira(x.net_minor)+' · '+date(x.created_at)}>{x.status==='PENDING'&&<><button className="primary-button" onClick={()=>act(x.id,()=>reviewWithdrawal(x.id,'APPROVED',reason))}>Approve</button><button className="secondary-button" onClick={()=>act(x.id,()=>reviewWithdrawal(x.id,'REJECTED',reason))}>Reject</button></>}</Row>)}</Panel>}
   {tab==='plans'&&<div className="grid gap-4 lg:grid-cols-[1fr_380px]"><Panel title="Investment plans">{data.plans.map((x:any)=><Row key={x.id} title={x.name+' · '+(x.active&&!x.deleted_at?'LIVE':'ARCHIVED')} meta={x.category+' · '+x.duration_days+' days · '+(Number(x.return_bps)/100).toFixed(2)+'% · '+naira(x.minimum_minor)+'–'+naira(x.maximum_minor)}><button className="secondary-button" onClick={()=>setPlan({id:x.id,name:x.name,description:x.description,category:x.category,minimumMinor:Number(x.minimum_minor),maximumMinor:Number(x.maximum_minor),returnBps:Number(x.return_bps),durationDays:Number(x.duration_days),terms:x.terms,purchaseBonusMinor:Number(x.purchase_bonus_minor||0),active:x.active,displayOrder:x.display_order})}>Edit</button><button className="secondary-button" onClick={()=>act(x.id,()=>archivePlan(x.id,!x.deleted_at,'Admin plan status change'))}>{x.deleted_at?<RotateCcw size={15}/>:<Archive size={15}/>} {x.deleted_at?'Restore':'Archive'}</button></Row>)}</Panel><Panel title={plan.id?'Edit plan':'Create plan'}><div className="grid gap-2">{['name','description','terms'].map(k=><input key={k} className="account-form" placeholder={k} value={plan[k]} onChange={e=>setPlan({...plan,[k]:e.target.value})}/>)}<select className="account-form" value={plan.category} onChange={e=>setPlan({...plan,category:e.target.value})}><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option></select>{[['minimumMinor','Minimum ₦'],['maximumMinor','Maximum ₦'],['returnBps','Return BPS'],['durationDays','Duration days'],['purchaseBonusMinor','Purchase bonus minor'],['displayOrder','Display order']].map((x:any)=><input key={x[0]} className="account-form" type="number" placeholder={x[1]} value={plan[x[0]]} onChange={e=>setPlan({...plan,[x[0]]:Number(e.target.value)})}/>)}<label className="admin-checkbox"><input type="checkbox" checked={plan.active} onChange={e=>setPlan({...plan,active:e.target.checked})}/> Active</label><button className="primary-button" onClick={()=>act('plan',()=>savePlan(plan))}><Save size={15}/>Save plan</button></div></Panel></div>}
   {tab==='referrals'&&<Panel title="Referral records">{data.referrals.map((x:any)=><Row key={x.id} title={x.status+' · '+naira(x.reward_minor)} meta={x.referrer_user_id+' → '+x.referred_user_id+' · '+date(x.created_at)}><button className="primary-button" onClick={()=>act(x.id,()=>updateReferral(x.id,'QUALIFIED',Number(x.reward_minor||0),'Admin qualification'))}>Qualify</button><button className="secondary-button" onClick={()=>act(x.id,()=>updateReferral(x.id,'PENDING',0,'Admin reset'))}>Reset</button></Row>)}</Panel>}
   {tab==='lucky'&&<div className="grid gap-4 lg:grid-cols-[1fr_380px]"><Panel title="Lucky Wish draws">{data.draws.map((x:any)=><Row key={x.id} title={x.status+' · '+x.title} meta={x.reward_type+' · '+naira(x.reward_minor||0)+' · '+date(x.closes_at)}><button className="secondary-button" onClick={()=>act(x.id,()=>toggleDraw(x.id,x.status!=='OPEN'))}>{x.status==='OPEN'?'Close':'Open'}</button></Row>)}</Panel><Panel title="Create draw"><div className="grid gap-2"><input className="account-form" placeholder="Title" value={draw.title} onChange={e=>setDraw({...draw,title:e.target.value})}/><input className="account-form" placeholder="Description" value={draw.description} onChange={e=>setDraw({...draw,description:e.target.value})}/><select className="account-form" value={draw.rewardType} onChange={e=>setDraw({...draw,rewardType:e.target.value})}><option>CASH</option><option>ALTERNATE</option></select><input className="account-form" type="number" placeholder="Reward ₦" value={draw.rewardMinor/100} onChange={e=>setDraw({...draw,rewardMinor:Math.round(Number(e.target.value)*100)})}/><input className="account-form" placeholder="Alternative reward" value={draw.alternateReward} onChange={e=>setDraw({...draw,alternateReward:e.target.value})}/><input className="account-form" type="number" placeholder="Entry cost ₦" value={draw.entryCostMinor/100} onChange={e=>setDraw({...draw,entryCostMinor:Math.round(Number(e.target.value)*100)})}/><input className="account-form" type="datetime-local" value={draw.opensAt} onChange={e=>setDraw({...draw,opensAt:e.target.value})}/><input className="account-form" type="datetime-local" value={draw.closesAt} onChange={e=>setDraw({...draw,closesAt:e.target.value})}/><button className="primary-button" onClick={()=>act('draw',()=>createDraw(draw))}>Create draw</button></div></Panel></div>}
   {tab==='notifications'&&<Panel title="Send notifications"><div className="grid gap-2 max-w-xl"><input className="account-form" placeholder="User UUID (blank = all active)" value={msg.userId} onChange={e=>setMsg({...msg,userId:e.target.value})}/><input className="account-form" placeholder="Title" value={msg.title} onChange={e=>setMsg({...msg,title:e.target.value})}/><textarea className="account-form min-h-32" placeholder="Message" value={msg.body} onChange={e=>setMsg({...msg,body:e.target.value})}/><button className="primary-button" onClick={()=>act('notify',()=>sendAdminNotification(msg.userId||null,msg.title,msg.body,msg.type))}><Send size={15}/>Send notification</button></div></Panel>}
   {tab==='accounts'&&<Panel title="Payment accounts"><a className="primary-button inline-flex" href="/admin/accounts">Open bank-account editor</a>{data.accounts.map((x:any)=><Row key={x.id} title={x.bank_name+' · '+(x.active?'VISIBLE':'HIDDEN')} meta={x.account_name+' · '+x.account_number}><button className="secondary-button" onClick={()=>act(x.id,()=>setPaymentAccountActive(x.id,!x.active))}>{x.active?'Hide':'Activate'}</button></Row>)}</Panel>}
   {tab==='payouts'&&<Panel title="User payout accounts">{data.payouts.filter((x:any)=>!x.deleted_at).map((x:any)=><Row key={x.id} title={x.bank_name+' · '+x.account_name} meta={x.user_id+' · '+x.account_number+(x.is_default?' · DEFAULT':'')}><button className="secondary-button" onClick={()=>act(x.id,()=>archivePayout(x.id,'Admin archived payout account'))}><Archive size={15}/>Archive</button></Row>)}</Panel>}
   {tab==='ledger'&&<Panel title="Financial ledger">{data.ledger.map((x:any)=><Row key={x.id} title={x.type+' · '+x.direction+' · '+naira(x.amount_minor)} meta={x.user_id+' · '+x.reference+' · '+date(x.created_at)}/>)}</Panel>}
   {tab==='audit'&&<Panel title="Audit log">{data.audits.map((x:any)=><Row key={x.id} title={x.action} meta={(x.actor_id||'system')+' · '+x.target_type+' · '+date(x.created_at)}>{x.reason&&<span className="text-xs opacity-60">{x.reason}</span>}</Row>)}</Panel>}
   {tab==='settings'&&<Panel title="Withdrawal policy"><div className="grid gap-2 max-w-xl"><input className="account-form" value={policy.timezone} onChange={e=>setPolicy({...policy,timezone:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className="account-form" type="time" value={policy.startTime} onChange={e=>setPolicy({...policy,startTime:e.target.value})}/><input className="account-form" type="time" value={policy.endTime} onChange={e=>setPolicy({...policy,endTime:e.target.value})}/></div><input className="account-form" type="number" value={policy.minimumMinor/100} onChange={e=>setPolicy({...policy,minimumMinor:Math.round(Number(e.target.value)*100)})} placeholder="Minimum withdrawal ₦"/><input className="account-form" type="number" value={policy.maximumMinor==null?'':policy.maximumMinor/100} onChange={e=>setPolicy({...policy,maximumMinor:e.target.value===''?null:Math.round(Number(e.target.value)*100)})} placeholder="Maximum withdrawal ₦"/><label className="admin-checkbox"><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/> Withdrawals enabled</label><button className="primary-button" onClick={()=>act('policy',()=>savePolicy(policy))}>Save policy</button></div></Panel>}
  </div>
 </div></main>
}
function Panel(p:any){return <section className="rounded-3xl border border-white/10 bg-white/5 p-5"><h2 className="mb-4 text-lg font-semibold">{p.title}</h2>{p.children}</section>}
function Row(p:any){return <article className="mb-2 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><div><strong className="block">{p.title}</strong><span className="text-xs opacity-60">{p.meta}</span></div><div className="flex flex-wrap gap-2">{p.children}</div></article>}
