'use client'

import { useState } from 'react'
import { ArrowDownToLine, ArrowLeft, ArrowUpRight, Check, ChevronRight, CircleHelp, Copy, Home, LogOut, Moon, Plus, Send, Settings, ShieldCheck, Sun, TrendingUp, Upload, Users, Wallet, X, Zap } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { signOut } from '@/lib/auth-client'
import { getPaymentAccounts, getPublicPlans, submitInvestmentProof } from '@/app/actions/investments'

type Category = 'DAILY' | 'WEEKLY' | 'MONTHLY'
type Plan = { id: string; name: string; description: string; category: string; minimumMinor: number; maximumMinor: number; returnBps: number; durationDays: number }
type Account = { id: string; label: string; bankName: string; accountName: string; accountNumber: string }
const fallbackPlans: Plan[] = [
  { id: 'daily-demo', name: 'Daily Growth', description: 'Short-cycle daily plan', category: 'DAILY', minimumMinor: 1000000, maximumMinor: 50000000, returnBps: 180, durationDays: 1 },
  { id: 'weekly-demo', name: 'Weekly Momentum', description: 'A focused weekly plan', category: 'WEEKLY', minimumMinor: 2500000, maximumMinor: 100000000, returnBps: 1500, durationDays: 7 },
  { id: 'monthly-demo', name: 'Monthly Horizon', description: 'Longer-term monthly growth', category: 'MONTHLY', minimumMinor: 5000000, maximumMinor: 250000000, returnBps: 6500, durationDays: 30 },
]
const categories: Category[] = ['DAILY', 'WEEKLY', 'MONTHLY']
const naira = (minor: number) => `₦${Math.round(minor / 100).toLocaleString('en-NG')}`

export default function Page() {
  const router = useRouter(); const [active, setActive] = useState<'home' | 'invest' | 'team' | 'my'>('home'); const [dark, setDark] = useState(true); const [screen, setScreen] = useState<string | null>(null); const [toast, setToast] = useState(''); const [category, setCategory] = useState<Category>('DAILY'); const [plans, setPlans] = useState<Plan[]>(fallbackPlans); const [selected, setSelected] = useState<Plan | null>(null); const [accounts, setAccounts] = useState<Account[]>([])
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2400) }
  const openInvest = async () => { setActive('invest'); try { const live = await getPublicPlans(); if (live.length) setPlans(live as Plan[]) } catch { notify('Showing available investment plans') } }
  const openPlan = async (plan: Plan) => { setSelected(plan); try { setAccounts((await getPaymentAccounts()) as Account[]) } catch { notify('Unable to load payment accounts') } }
  async function logout() { await signOut(); router.replace('/sign-in'); router.refresh() }
  return <main className={dark ? 'quantix-shell dark' : 'quantix-shell light'}><div className="app-frame"><header className="topbar"><div className="brand-lockup"><div className="brand-mark"><Zap size={17} fill="currentColor" /></div><div><strong>quantix</strong><span>PRIME</span></div></div><div className="top-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="avatar" onClick={() => setActive('my')}>MC</button></div></header><div className="screen-content">{screen ? <Subpage screen={screen} back={() => setScreen(null)} notify={notify} /> : active === 'home' ? <HomeView openInvest={openInvest} go={setScreen} /> : active === 'invest' ? <InvestView category={category} setCategory={setCategory} plans={plans} openPlan={openPlan} go={setScreen} /> : active === 'team' ? <TeamView notify={notify} /> : <MyView go={setScreen} logout={logout} />}</div>{!screen && <nav className="bottom-nav" aria-label="Primary navigation"><button className={active === 'home' ? 'nav-item active' : 'nav-item'} onClick={() => setActive('home')}><Home /><span>Home</span></button><button className={active === 'invest' ? 'nav-item active' : 'nav-item'} onClick={openInvest}><TrendingUp /><span>Invest</span></button><button className={active === 'team' ? 'nav-item active' : 'nav-item'} onClick={() => setActive('team')}><Users /><span>Team</span></button><button className={active === 'my' ? 'nav-item active' : 'nav-item'} onClick={() => setActive('my')}><ShieldCheck /><span>My</span></button></nav>}</div>{selected && <InvestmentSheet plan={selected} accounts={accounts} close={() => setSelected(null)} notify={notify} />}{toast && <div className="toast" role="status">{toast}</div>}</main>
}
function Header({ eyebrow, title, back }: { eyebrow?: string; title: string; back?: () => void }) { return <div className="page-header">{back && <button className="back-button" onClick={back}><ArrowLeft size={18} /></button>}<div className={back ? 'header-copy' : ''}>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1></div></div> }
function HomeView({ openInvest, go }: { openInvest: () => void; go: (s: string) => void }) { return <><Header eyebrow="Tuesday, June 24" title="Good morning, Maya" /><section className="balance-card"><div className="balance-top"><span>Total balance <CircleHelp size={14} /></span><span className="live-pill"><i /> Live</span></div><strong>₦12,840,720</strong><div className="balance-meta"><span>+₦482,160 this month</span><span>+3.9%</span></div><div className="sparkline">{Array.from({ length: 10 }, (_, i) => <span key={i} />)}</div></section><div className="quick-grid"><Quick icon={ArrowDownToLine} label="Deposit" onClick={() => go('deposit')} /><Quick icon={ArrowUpRight} label="Withdraw" onClick={() => go('withdraw')} /><Quick icon={TrendingUp} label="Invest" onClick={openInvest} /><Quick icon={Users} label="Invite" onClick={() => go('team')} /></div><section className="section-block"><div className="section-heading"><h2>Investment snapshot</h2><button className="text-button" onClick={openInvest}>View plans</button></div><div className="activity-list"><div className="activity-row"><div className="activity-icon emerald"><TrendingUp size={17} /></div><div className="activity-copy"><strong>Plans are ready to fund</strong><span>Choose Daily, Weekly, or Monthly growth</span></div><ChevronRight size={17} /></div></div></section></> }
function Quick({ icon: Icon, label, onClick }: any) { return <button className="quick-action" onClick={onClick}><span><Icon size={19} /></span>{label}</button> }
function InvestView({ category, setCategory, plans, openPlan, go }: any) { const visible = plans.filter((p: Plan) => p.category === category); return <><Header eyebrow="Build your balance" title="Invest" /><div className="category-tabs">{categories.map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item[0] + item.slice(1).toLowerCase()}</button>)}</div><div className="notice"><ShieldCheck size={18} /><p><strong>Transparent individual plans.</strong><br />Review your projected interest and final maturity payout before funding.</p></div><section className="section-block"><div className="section-heading"><h2>{category[0] + category.slice(1).toLowerCase()} plans</h2><span className="muted">{visible.length} available</span></div><div className="plan-list">{visible.map((p: Plan) => <PlanCard key={p.id} plan={p} openPlan={openPlan} />)}</div></section><section className="section-block"><div className="section-heading"><h2>Pending requests</h2><button className="text-button" onClick={() => go('history')}>History</button></div><p className="muted">Payment proof requests are reviewed by the Quantix operations team.</p></section></> }
function PlanCard({ plan, openPlan }: any) { const [amount, setAmount] = useState(plan.minimumMinor); const interest = Math.round(amount * plan.returnBps / 10000); return <div className="plan-card emerald"><div className="plan-line"><span className="plan-badge">{plan.durationDays} days</span><b>{(plan.returnBps / 100).toFixed(2)}% return</b></div><strong>{plan.name}</strong><p className="plan-description">{plan.description}</p><label className="amount-label">Investment amount<input type="number" min={plan.minimumMinor / 100} max={plan.maximumMinor / 100} value={Math.round(amount / 100)} onChange={(e) => setAmount(Math.max(0, Number(e.target.value) * 100))} /></label><div className="plan-calcs"><span><small>Projected interest</small><b>{naira(interest)}</b></span><span><small>Cumulative return</small><b>{naira(amount + interest)}</b></span><span><small>Maturity payout</small><b>{naira(amount + interest)}</b></span></div><button className="primary-button full" onClick={() => openPlan(plan)}>Invest with payment proof <ArrowUpRight size={16} /></button><p className="plan-range">Min {naira(plan.minimumMinor)} · Max {naira(plan.maximumMinor)}</p></div> }
function InvestmentSheet({ plan, accounts, close, notify }: any) { const [account, setAccount] = useState(''); const [amount, setAmount] = useState(plan.minimumMinor); const [reference, setReference] = useState(''); const [proof, setProof] = useState(''); const [pending, setPending] = useState(false); async function submit() { if (!account || !reference || !proof) return notify('Select an account and attach payment proof'); setPending(true); try { await submitInvestmentProof({ planId: plan.id, paymentAccountId: account, amountMinor: amount, transferReference: reference, proofName: proof }); notify('Investment request submitted for review'); close() } catch { notify('Unable to submit request') } finally { setPending(false) } } return <div className="sheet-backdrop" onClick={close}><section className="sheet" onClick={(e) => e.stopPropagation()}><div className="sheet-handle" /><div className="sheet-title"><div><p className="eyebrow">Fund {plan.name}</p><h2>Payment proof</h2></div><button className="icon-button" onClick={close}><X size={18} /></button></div><p className="sheet-copy">Select an admin-configured account, make your transfer, then submit the receipt for review.</p><label>Amount<input type="number" value={Math.round(amount / 100)} onChange={(e) => setAmount(Number(e.target.value) * 100)} /></label><div className="account-options">{accounts.length ? accounts.map((item) => <button key={item.id} className={account === item.id ? 'account-option selected' : 'account-option'} onClick={() => setAccount(item.id)}><Wallet size={17} /><span><b>{item.bankName}</b><small>{item.accountName} · {item.accountNumber}</small></span>{account === item.id && <Check size={17} />}</button>) : <p className="form-note">No payment accounts are currently active. Please check back shortly.</p>}</div><label>Transfer reference<input value={reference} onChange={(e) => setReference(e.target.value)} placeholder="Bank transfer reference" /></label><label>Payment proof<div className="upload-field"><Upload size={18} />{proof || 'Attach receipt'}<input type="file" accept="image/*,.pdf" onChange={(e) => setProof(e.target.files?.[0]?.name || '')} /></div></label><button className="primary-button full" disabled={pending || !accounts.length} onClick={submit}>{pending ? 'Submitting…' : 'Submit for review'} <ArrowUpRight size={16} /></button></section></div> }
function TeamView({ notify }: any) { return <><Header eyebrow="Your community" title="Team" /><section className="referral-card"><p className="eyebrow">Your invite code</p><div className="referral-code"><strong>MX7-QP24</strong><button onClick={() => notify('Invite code copied')}><Copy size={16} /></button></div><p>Share your code with people you know and grow together.</p><button className="primary-button" onClick={() => notify('Share sheet opened')}>Share invite <Send size={16} /></button></section><div className="metric-row"><Metric value="18" label="Members" /><Metric value="₦216k" label="Rewards" /><Metric value="92%" label="Active" /></div></> }
function Metric({ value, label }: any) { return <div className="metric"><strong>{value}</strong><span>{label}</span></div> }
function MyView({ go, logout }: any) { return <><Header eyebrow="Account center" title="My" /><button className="profile-card" onClick={() => go('profile')}><div className="profile-avatar">MC</div><div><strong>Maya Chen</strong><span>Prime member since 2024</span><div className="verified"><ShieldCheck size={13} /> Identity verified</div></div><ChevronRight size={18} /></button><section className="menu-list"><Menu icon={Wallet} label="Wallet & payment methods" onClick={() => go('wallet')} /><Menu icon={ArrowDownToLine} label="Deposit funds" onClick={() => go('deposit')} /><Menu icon={ArrowUpRight} label="Withdraw funds" onClick={() => go('withdraw')} /><Menu icon={Settings} label="Settings & FAQ" onClick={() => go('settings')} /></section><button className="secondary-button full" onClick={logout}><LogOut size={16} /> Log out securely</button></> }
function Menu({ icon: Icon, label, onClick }: any) { return <button onClick={onClick}><span className="menu-icon"><Icon size={17} /></span><strong>{label}</strong><ChevronRight size={17} /></button> }
function Subpage({ screen, back, notify }: any) { return <><Header eyebrow="Account" title={screen[0].toUpperCase() + screen.slice(1)} back={back} /><section className="form-card"><div className="verification-icon"><ShieldCheck size={24} /></div><h2>{screen === 'deposit' ? 'Fund your account' : screen === 'withdraw' ? 'Move your funds' : 'Account details'}</h2><p>Use the secure Quantix workflow to manage your account. Requests are reviewed and recorded against your profile.</p>{screen === 'deposit' && <button className="primary-button full" onClick={() => notify('Open Invest to fund a plan with proof')}>Go to investment plans <TrendingUp size={16} /></button>}{screen !== 'deposit' && <button className="secondary-button full" onClick={() => notify('Request received for review')}>Submit request <ArrowUpRight size={16} /></button>}</section></> }
