'use client'

import { useState } from 'react'
import { ArrowDownToLine, ArrowLeft, ArrowUpRight, Bot, Check, ChevronRight, CircleHelp, Copy, Download, Eye, Gift, Home, LockKeyhole, LogOut, MessageCircle, Moon, MoreHorizontal, Plus, QrCode, Search, Send, Settings, ShieldCheck, Sparkles, Sun, Target, TrendingUp, Upload, Users, Wallet, X, Zap } from 'lucide-react'

type Tab = 'home' | 'lucky' | 'invest' | 'team' | 'support' | 'my'
type Screen = { name: string; returnTo?: string }
type Plan = { name: string; term: string; rate: string; min: string; accent: string }

const tabs = [
  { id: 'home' as const, label: 'Home', icon: Home }, { id: 'lucky' as const, label: 'Lucky Wish', icon: Gift },
  { id: 'invest' as const, label: 'Invest', icon: TrendingUp }, { id: 'team' as const, label: 'Team', icon: Users },
  { id: 'support' as const, label: 'AI Support', icon: Bot }, { id: 'my' as const, label: 'My', icon: ShieldCheck },
]
const plans: Plan[] = [
  { name: 'Quantix Starter', term: '30 days', rate: '8.4%', min: '₦100,000', accent: 'cyan' },
  { name: 'Quantix Momentum', term: '90 days', rate: '13.8%', min: '₦500,000', accent: 'emerald' },
  { name: 'Quantix Horizon', term: '180 days', rate: '28.5%', min: '₦1,000,000', accent: 'amber' },
]
const activities = [['Investment matured', '+₦62,400', 'Today, 09:42'], ['Referral reward', '+₦12,000', 'Yesterday, 16:18'], ['Withdrawal', '-₦80,000', 'Jun 18, 11:05']]

export default function Page() {
  const [active, setActive] = useState<Tab>('home')
  const [screen, setScreen] = useState<Screen | null>(null)
  const [dark, setDark] = useState(true)
  const [toast, setToast] = useState('')
  const [selectedPlan, setSelectedPlan] = useState<Plan | null>(null)
  const [accounts, setAccounts] = useState(['GTBank •••• 2984'])
  const [verified, setVerified] = useState(false)
  const [message, setMessage] = useState('')
  const [chat, setChat] = useState(['Hi Maya, I’m Quantix AI. What can I help you with today?'])
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2400) }
  const go = (name: string) => setScreen({ name })
  const back = () => setScreen(null)
  const sendMessage = () => { if (!message.trim()) return; setChat((c) => [...c, message.trim(), 'I can help with balances, plan terms, deposits, withdrawals, and account security.']); setMessage('') }

  return <main className={dark ? 'quantix-shell dark' : 'quantix-shell light'}><div className="app-frame">
    <header className="topbar"><div className="brand-lockup"><div className="brand-mark"><Zap size={17} fill="currentColor" /></div><div><strong>quantix</strong><span>PRIME</span></div></div><div className="top-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="avatar" onClick={() => { setActive('my'); back() }}>MC</button></div></header>
    <div className="screen-content">{screen ? <Subpage screen={screen.name} accounts={accounts} setAccounts={setAccounts} verified={verified} setVerified={setVerified} notify={notify} back={back} returnTo={screen.returnTo} /> : <><TabView active={active} setActive={setActive} notify={notify} go={go} chat={chat} message={message} setMessage={setMessage} sendMessage={sendMessage} setSelectedPlan={setSelectedPlan} /></>}</div>
    {!screen && <nav className="bottom-nav" aria-label="Primary navigation">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={active === id ? 'nav-item active' : 'nav-item'} onClick={() => setActive(id)} aria-current={active === id ? 'page' : undefined}><Icon /><span>{label}</span></button>)}</nav>}
  </div>{selectedPlan && <PlanSheet plan={selectedPlan} onClose={() => setSelectedPlan(null)} notify={notify} go={go} />}{toast && <div className="toast" role="status"><Sparkles size={16} />{toast}</div>}</main>
}

function TabView({ active, setActive, notify, go, chat, message, setMessage, sendMessage, setSelectedPlan }: any) {
  if (active === 'home') return <HomeView notify={notify} setActive={setActive} go={go} />
  if (active === 'lucky') return <LuckyView notify={notify} go={go} />
  if (active === 'invest') return <InvestView setSelectedPlan={setSelectedPlan} go={go} />
  if (active === 'team') return <TeamView notify={notify} go={go} />
  if (active === 'support') return <SupportView chat={chat} message={message} setMessage={setMessage} sendMessage={sendMessage} />
  return <MyView notify={notify} go={go} />
}
function Header({ eyebrow, title, back, action }: { eyebrow?: string; title: string; back?: () => void; action?: React.ReactNode }) { return <div className="page-header">{back && <button className="back-button" onClick={back}><ArrowLeft size={18} /></button>}<div className={back ? 'header-copy' : ''}>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1></div>{action}</div> }
function HomeView({ notify, setActive, go }: any) { return <><Header eyebrow="Tuesday, June 24" title="Good morning, Maya" action={<button className="notification-dot" onClick={() => notify('You are all caught up')}><MessageCircle size={19} /></button>} /><section className="balance-card"><div className="balance-top"><span>Total balance <CircleHelp size={14} /></span><span className="live-pill"><i /> Live</span></div><strong>₦12,840,720</strong><div className="balance-meta"><span>+₦482,160 this month</span><span>+3.9%</span></div><div className="sparkline">{Array.from({ length: 10 }, (_, i) => <span key={i} />)}</div></section><div className="quick-grid"><Quick icon={ArrowDownToLine} label="Deposit" onClick={() => go('deposit')} /><Quick icon={ArrowUpRight} label="Withdraw" onClick={() => go('withdraw')} /><Quick icon={TrendingUp} label="Invest" onClick={() => setActive('invest')} /><Quick icon={Users} label="Invite" onClick={() => setActive('team')} /></div><section className="section-block"><div className="section-heading"><h2>Community pulse</h2><span className="verified"><ShieldCheck size={14} /> Verified</span></div><button className="community-card" onClick={() => go('community')}><div className="community-icon"><Users size={22} /></div><div><strong>1,248 members growing</strong><p>Your network is 12% more active this week.</p></div><ChevronRight size={18} /></button></section><section className="section-block"><div className="section-heading"><h2>Recent activity</h2><button className="text-button" onClick={() => go('history')}>View all</button></div><div className="activity-list">{activities.map(([title, amount, date]) => <div className="activity-row" key={title}><div className="activity-icon"><Wallet size={17} /></div><div className="activity-copy"><strong>{title}</strong><span>{date}</span></div><b className={amount.startsWith('+') ? 'positive' : 'negative'}>{amount}</b></div>)}</div></section></> }
function Quick({ icon: Icon, label, onClick }: any) { return <button className="quick-action" onClick={onClick}><span><Icon size={19} /></span>{label}</button> }
function LuckyView({ notify, go }: any) { return <><Header eyebrow="Community campaign" title="Lucky Wish" action={<button className="icon-button" onClick={() => go('lucky-rules')}><CircleHelp size={18} /></button>} /><section className="lucky-hero"><div className="lucky-orbit"><Gift size={30} /></div><p className="eyebrow">Next draw in</p><div className="countdown"><b>04</b><span>:</span><b>18</b><span>:</span><b>32</b></div><p>Hours &nbsp; Minutes &nbsp; Seconds</p></section><div className="metric-row"><Metric value="24/30" label="Entries" /><Metric value="₦180k" label="Your goal" /><Metric value="60%" label="Progress" /></div><section className="section-block"><div className="section-heading"><h2>How to qualify</h2><button className="text-button" onClick={() => go('lucky-entries')}>My entries</button></div><div className="goal-list"><Goal done title="Complete your profile" detail="Verified and ready" /><Goal done title="Invite 3 community members" detail="3 of 3 completed" /><Goal title="Make an eligible investment" detail="₦320,000 remaining" /></div><button className="primary-button full" onClick={() => notify('Your entry is saved for the next draw')}>Save my entry <ArrowUpRight size={16} /></button></section></> }
function Metric({ value, label }: any) { return <div className="metric"><strong>{value}</strong><span>{label}</span></div> }
function Goal({ done, title, detail }: any) { return <div className="goal"><div className={done ? 'check done' : 'check'}>{done && <Check size={13} />}</div><div><strong>{title}</strong><span>{detail}</span></div><ChevronRight size={16} /></div> }
function InvestView({ setSelectedPlan, go }: any) { return <><Header eyebrow="Build your balance" title="Invest" action={<button className="icon-button" onClick={() => go('eligibility')}><CircleHelp size={18} /></button>} /><div className="notice"><ShieldCheck size={18} /><p><strong>Clear terms, visible snapshots.</strong><br />Individual plans configured by Quantix. No pooled funds.</p></div><section className="section-block"><div className="section-heading"><h2>Available plans</h2><span className="muted">3 plans</span></div><div className="plan-list">{plans.map((p) => <button className={`plan-card ${p.accent}`} key={p.name} onClick={() => setSelectedPlan(p)}><div className="plan-line"><span className="plan-badge">{p.term}</span><ChevronRight size={17} /></div><strong>{p.name}</strong><div className="plan-stats"><span><b>{p.rate}</b><small>Fixed return</small></span><span><b>{p.min}</b><small>Minimum</small></span></div></button>)}</div></section><section className="section-block"><div className="section-heading"><h2>Your investments</h2><button className="text-button" onClick={() => go('history')}>History</button></div><div className="investment-row"><div className="activity-icon emerald"><TrendingUp size={17} /></div><div className="activity-copy"><strong>Quantix Momentum</strong><span>Matures Sep 22, 2026</span></div><b className="positive">+₦62,400</b></div></section></> }
function PlanSheet({ plan, onClose, notify, go }: any) { return <div className="sheet-backdrop" onClick={onClose}><section className="sheet" onClick={(e) => e.stopPropagation()}><div className="sheet-handle" /><div className="sheet-title"><div><p className="eyebrow">Plan details</p><h2>{plan.name}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div><div className="detail-rate"><strong>{plan.rate}</strong><span>fixed return over {plan.term}</span></div><div className="formula"><span>Projected return</span><b>principal × {plan.rate}</b></div><div className="detail-points"><div><ShieldCheck size={17} /><span>Community eligibility required</span></div><div><LockKeyhole size={17} /><span>Snapshot locked after confirmation</span></div><div><Target size={17} /><span>Minimum starting balance: {plan.min}</span></div></div><button className="primary-button full" onClick={() => { notify('Eligibility check started'); onClose(); go('eligibility') }}>Check eligibility <ArrowUpRight size={16} /></button></section></div> }
function TeamView({ notify, go }: any) { return <><Header eyebrow="Your community" title="Team" action={<button className="icon-button" onClick={() => go('team-qr')}><QrCode size={18} /></button>} /><section className="referral-card"><p className="eyebrow">Your invite code</p><div className="referral-code"><strong>MX7-QP24</strong><button onClick={() => notify('Invite code copied')}><Copy size={16} /></button></div><p>Share your code with people you know and grow together.</p><button className="primary-button" onClick={() => notify('Share sheet opened')}>Share invite <Send size={16} /></button></section><div className="metric-row"><Metric value="18" label="Members" /><Metric value="₦216k" label="Rewards" /><Metric value="92%" label="Active" /></div><section className="section-block"><div className="section-heading"><h2>Referral history</h2><button className="text-button" onClick={() => go('rewards')}>Rewards</button></div><div className="referral-list"><Member initials="AL" name="Alex L." amount="+₦12k" /><Member initials="JR" name="Jordan R." amount="+₦12k" coral /><button className="secondary-button full" onClick={() => go('team-members')}>View all referrals <ChevronRight size={16} /></button></div></section></> }
function Member({ initials, name, amount, coral }: any) { return <div className="member-row"><div className={coral ? 'avatar small coral' : 'avatar small'}>{initials}</div><div className="activity-copy"><strong>{name}</strong><span>Joined this month</span></div><b className="positive">{amount}</b></div> }
function SupportView({ chat, message, setMessage, sendMessage }: any) { return <><Header eyebrow="Always here" title="AI Support" action={<span className="live-pill"><i /> Online</span>} /><div className="topic-grid"><button onClick={() => setMessage('How do I make a withdrawal?')}><Wallet size={17} />Withdrawals</button><button onClick={() => setMessage('Explain my investment return')}><TrendingUp size={17} />Investments</button><button onClick={() => setMessage('How is my account protected?')}><ShieldCheck size={17} />Security</button></div><div className="chat-card"><div className="chat-head"><div className="bot-avatar"><Bot size={19} /></div><div><strong>Quantix AI</strong><span>Replies instantly</span></div></div><div className="chat-messages">{chat.map((item: string, i: number) => <div key={`${item}-${i}`} className={i % 2 === 0 ? 'bubble user' : 'bubble bot'}>{item}</div>)}</div><div className="chat-composer"><input aria-label="Message Quantix AI" placeholder="Ask anything..." value={message} onChange={(e) => setMessage(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && sendMessage()} /><button onClick={sendMessage}><Send size={17} /></button></div></div><button className="escalate"><MessageCircle size={17} /> Need a human? Contact support</button></> }
function MyView({ notify, go }: any) { return <><Header eyebrow="Account center" title="My" action={<button className="icon-button" onClick={() => go('settings')}><Settings size={18} /></button>} /><button className="profile-card" onClick={() => go('profile')}><div className="profile-avatar">MC</div><div><strong>Maya Chen</strong><span>Prime member since 2024</span><div className="verified"><ShieldCheck size={13} /> Identity verified</div></div><ChevronRight size={18} /></button><section className="section-block"><div className="section-heading"><h2>Account overview</h2></div><div className="overview-grid"><Metric value="₦12.8m" label="Balance" /><Metric value="4" label="Active plans" /><Metric value="18" label="Team members" /></div></section><section className="menu-list"><Menu icon={Wallet} label="Wallet & payment methods" onClick={() => go('wallet')} /><Menu icon={ArrowDownToLine} label="Deposit funds" onClick={() => go('deposit')} /><Menu icon={ArrowUpRight} label="Withdraw funds" onClick={() => go('withdraw')} /><Menu icon={ShieldCheck} label="Security & payment password" onClick={() => go('security')} /><Menu icon={Settings} label="Settings & FAQ" onClick={() => go('settings')} /></section><button className="secondary-button full" onClick={() => notify('Signed out of this demo')}><LogOut size={16} /> Log out of demo</button></> }
function Menu({ icon: Icon, label, onClick }: any) { return <button onClick={onClick}><span className="menu-icon"><Icon size={17} /></span><strong>{label}</strong><ChevronRight size={17} /></button> }

function Subpage({ screen, back, notify, accounts, setAccounts, verified, setVerified, returnTo }: any) {
  const [value, setValue] = useState('');
  const [submitted, setSubmitted] = useState(false)
  if (screen === 'community') return <><Header eyebrow="Community access" title="Join Quantix Prime" back={back} /><section className="form-card"><div className="verification-icon"><Users size={24} /></div><h2>Welcome to the community</h2><p>Join verified members to unlock investing, referrals, and Lucky Wish entries.</p><label>Invite code<input value={value} onChange={(e) => setValue(e.target.value)} placeholder="e.g. MX7-QP24" /></label><button className="primary-button full" onClick={() => { setSubmitted(true); notify('Community request submitted for review') }}>{submitted ? 'Submitted for review' : 'Request access'}</button><p className="form-note"><ShieldCheck size={14} /> Quantix reviews eligibility on the server before access is granted.</p></section></>
  if (screen === 'deposit') return <><Header eyebrow="Fund your account" title="Deposit" back={back} /><section className="form-card"><div className="section-heading"><h2>Quantix Prime account</h2><span className="verified"><ShieldCheck size={13} /> Verified</span></div><div className="bank-details"><span>Bank</span><strong>Providus Bank</strong><span>Account number</span><strong>1029384756 <Copy size={14} /></strong><span>Account name</span><strong>Maya Chen / Quantix Prime</strong></div><button className="secondary-button full" onClick={() => notify('Bank details copied')}><Copy size={16} /> Copy account details</button><label>Amount to deposit<input inputMode="numeric" placeholder="₦0.00" /></label><label>Proof of payment<div className="upload-field"><Upload size={18} /> Upload receipt<input type="file" /></div></label><button className="primary-button full" onClick={() => notify('Deposit proof submitted for review')}>Submit deposit proof <ArrowUpRight size={16} /></button><p className="form-note">Deposits are matched and credited after review. Never send funds to an unverified account.</p></section></>
  if (screen === 'withdraw') return <><Header eyebrow="Move your funds" title="Withdraw" back={back} /><section className="form-card"><div className="notice compact"><ShieldCheck size={17} /><p>Withdrawals are reviewed for account safety and usually arrive within 1–2 business days.</p></div><label>Amount<input inputMode="numeric" placeholder="₦0.00" /></label><div className="section-heading"><h2>Send to</h2><button className="text-button" onClick={() => setAccounts((a: string[]) => [...a, 'Access Bank •••• 8402'])}><Plus size={14} /> Add account</button></div>{accounts.map((a: string) => <button className="choice-row" key={a} onClick={() => notify(`${a} selected`)}><Wallet size={17} /><span>{a}</span><Check size={16} /></button>)}<button className="primary-button full" onClick={() => notify('Withdrawal request submitted')}>Review withdrawal <ArrowUpRight size={16} /></button><p className="form-note">A payment password may be required to confirm this transaction.</p></section></>
  if (screen === 'wallet') return <><Header eyebrow="Payout settings" title="Wallet" back={back} /><section className="form-card"><div className="section-heading"><h2>Saved accounts</h2><span className="muted">{accounts.length}/2 slots</span></div>{accounts.map((a: string, i: number) => <div className="choice-row" key={a}><Wallet size={17} /><span>{a}<small>Available for withdrawals</small></span><button onClick={() => setAccounts((all: string[]) => all.filter((_, index) => index !== i))}><X size={16} /></button></div>)}{accounts.length < 2 && <button className="secondary-button full" onClick={() => setAccounts((a: string[]) => [...a, 'Access Bank •••• 8402'])}><Plus size={16} /> Add payout account</button>}<p className="form-note"><LockKeyhole size={14} /> Only two payout accounts can be saved for your protection.</p></section></>
  if (screen === 'security') return <><Header eyebrow="Protect your account" title="Security" back={back} /><section className="form-card"><div className="verification-icon"><LockKeyhole size={24} /></div><h2>Set a payment password</h2><p>Use a separate password to confirm withdrawals and sensitive changes.</p><label>New payment password<input type="password" placeholder="Minimum 6 characters" /></label><label>Confirm password<input type="password" placeholder="Repeat password" /></label><button className="primary-button full" onClick={() => { notify('Payment password updated'); back() }}>Save payment password</button><div className="security-row"><ShieldCheck size={18} /><span><strong>Two-step review</strong><small>Transaction checks remain enabled.</small></span><Check size={17} /></div></section></>
  if (screen === 'profile') return <><Header eyebrow="Identity" title="Profile" back={back} /><section className="form-card"><div className="profile-large"><div className="profile-avatar">MC</div><div><h2>Maya Chen</h2><span className="verified"><ShieldCheck size={13} /> Identity verified</span></div></div><label>Full name<input defaultValue="Maya Chen" /></label><label>Email address<input defaultValue="maya.chen@example.com" /></label><label>Phone number<input defaultValue="+234 801 234 5678" /></label><button className="primary-button full" onClick={() => notify('Profile changes saved')}>Save profile</button></section></>
  if (screen === 'settings') return <><Header eyebrow="Preferences" title="Settings & help" back={back} /><section className="menu-list settings-list"><Menu icon={Settings} label="Notification preferences" onClick={() => notify('Notification preferences opened')} /><Menu icon={CircleHelp} label="Frequently asked questions" onClick={() => goToFaq(notify)} /><Menu icon={ShieldCheck} label="Terms & privacy" onClick={() => notify('Terms and privacy opened')} /><Menu icon={LogOut} label="Sign out" onClick={() => notify('Signed out of this demo')} /></section><div className="notice compact"><Bot size={17} /><p><strong>Need help?</strong><br />AI Support is available around the clock.</p></div></>
  if (screen === 'history') return <><Header eyebrow="Your records" title="History" back={back} /><div className="history-tabs"><button className="active">All</button><button>Investments</button><button>Money movement</button></div><section className="activity-list history-list">{activities.concat([['Deposit credited', '+₦250,000', 'Jun 15, 14:08'], ['Plan purchased', '-₦500,000', 'Jun 12, 09:20']]).map(([a, b, c]) => <div className="activity-row" key={a}><div className="activity-icon"><Wallet size={17} /></div><div className="activity-copy"><strong>{a}</strong><span>{c}</span></div><b className={b.startsWith('+') ? 'positive' : 'negative'}>{b}</b></div>)}</section></>
  if (screen === 'eligibility') return <><Header eyebrow="Before you invest" title="Eligibility check" back={back} /><section className="form-card"><div className="verification-icon"><ShieldCheck size={24} /></div><h2>One more step</h2><p>Your community access and balance are checked before an investment can be confirmed.</p><div className="check-list"><div><Check size={15} /> Community membership active</div><div><Check size={15} /> Identity verification complete</div><div><Eye size={15} /> Balance confirmation pending</div></div><button className="primary-button full" onClick={() => { setVerified(true); notify('Eligibility confirmed for this demo'); back() }}>Run server eligibility check</button><p className="form-note">This screen is a demo of the review state. Production checks must run on the server.</p></section></>
  if (screen === 'lucky-rules') return <><Header eyebrow="Lucky Wish" title="Rules & eligibility" back={back} /><section className="form-card"><h2>Earn entries fairly</h2><p>Complete verified account actions, invite eligible community members, and maintain an active individual plan.</p><div className="check-list"><div><Gift size={15} /> One entry per completed milestone</div><div><ShieldCheck size={15} /> Entries are reviewed before each draw</div><div><TrophyIcon /> Winners are announced in the community</div></div><button className="primary-button full" onClick={back}>Back to Lucky Wish</button></section></>
  if (screen === 'lucky-entries') return <><Header eyebrow="Lucky Wish" title="My entries" back={back} /><section className="form-card"><div className="entry-ticket"><Gift size={22} /><div><strong>June community draw</strong><span>24 confirmed entries</span></div><MoreHorizontal size={18} /></div><div className="entry-ticket"><Check size={22} /><div><strong>Profile verified</strong><span>Entry confirmed</span></div></div><button className="secondary-button full" onClick={() => notify('Entry receipt downloaded')}><Download size={16} /> Download receipt</button></section></>
  if (screen === 'team-qr') return <><Header eyebrow="Share your invite" title="Team QR" back={back} /><section className="form-card qr-card"><div className="qr-placeholder"><QrCode size={102} /></div><h2>Scan to join Maya&apos;s community</h2><p>Invite code MX7-QP24</p><button className="primary-button full" onClick={() => notify('Invite link copied')}><Copy size={16} /> Copy invite link</button></section></>
  if (screen === 'rewards') return <><Header eyebrow="Team performance" title="Rewards" back={back} /><div className="metric-row"><Metric value="₦216k" label="All time" /><Metric value="₦24k" label="This month" /><Metric value="18" label="Members" /></div><section className="form-card"><h2>Reward milestones</h2><div className="check-list"><div><Check size={15} /> 10 active members — completed</div><div><Target size={15} /> 25 active members — ₦50,000 bonus</div></div></section></>
  if (screen === 'team-members') return <><Header eyebrow="Community" title="All referrals" back={back} /><section className="activity-list"><Member initials="AL" name="Alex L." amount="Active" /><Member initials="JR" name="Jordan R." amount="Active" coral /><Member initials="TS" name="Tomi S." amount="Pending" /></section></>
  return <><Header title="Page" back={back} /><section className="form-card"><h2>Coming soon</h2><p>This Quantix Prime workflow is being prepared.</p></section></>
}
function goToFaq(notify: any) { notify('FAQ opened') }
function TrophyIcon() { return <Gift size={15} /> }
